### ISSUE TITLE
[PE-D][Tester B] Add command does not follow user guide for adding duplicate names

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14a-4/tp#332]
According to the User Guide, `Two contacts are considered duplicates if they share the same name, email, or phone number.`. Hence, according to the User Guide, I am unable to add 2 individuals named `John`. However, I am able to add `John` and `john`. Both should be considered the same name by the User Guide's logic.

![image.png](https://raw.githubusercontent.com/Vatinius/ped/main/files/affc1267-3130-4c2a-908b-92c48fba7c9e.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Vatinius/ped#10

**Comment by KrashKart** [comment]
Nope, sir Vatinius, you are incorrect yet again. Our User Guide is correct, but our logic behind this is a feature flaw. "John" and "john" are different names, thus "I am unable to add 2 contacts named `John`" is not a correct claim because you did **not** try to add 2 contacts with the name `John`.
